language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
install:
  - pip install -e .[test]
  - pip install coveralls
script:
  - pytest --cov ./test/unit/ ./test/integration/
after_success:
  - coveralls
